name: Do Not Merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled

jobs:
  fail-for-skip-merge:
    if: startWith(github.event.pull_request.labels.*.name, 'changelog:')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is a draft
        run: |
          echo "This PR has marked as Do Not Merge."
          exit 1
